In [26]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [27]:
df=datasets.load_iris(as_frame=True).frame
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [28]:
X=df.drop("target",axis=1)
y=df["target"]

In [29]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.3,random_state=42,stratify=y
)

In [30]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [31]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [23]:
 svc=SVC()
svc.fit(X_train_scaled,y_train)
y_pred=svc.predict(X_test_scaled)

In [24]:
from sklearn.metrics import accuracy_score, classification_report

print("accuracy : ",accuracy_score(y_test,y_pred))
print("classification report : ",classification_report(y_test,y_pred))

accuracy :  0.9333333333333333
classification report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [34]:
#linear kernal
svc=SVC(kernel="linear")
svc.fit(X_train_scaled,y_train)
y_pred=svc.predict(X_test_scaled)

print("accuracy : ",accuracy_score(y_test,y_pred))
print("classification report : ",classification_report(y_test,y_pred))

accuracy :  0.9111111111111111
classification report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.82      0.93      0.88        15
           2       0.92      0.80      0.86        15

    accuracy                           0.91        45
   macro avg       0.92      0.91      0.91        45
weighted avg       0.92      0.91      0.91        45

In [35]:
#polynomial kernal
svc=SVC(kernel="poly")
svc.fit(X_train_scaled,y_train)
y_pred=svc.predict(X_test_scaled)

print("accuracy : ",accuracy_score(y_test,y_pred))
print("classification report : ",classification_report(y_test,y_pred))

accuracy :  0.8666666666666667
classification report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.71      1.00      0.83        15
           2       1.00      0.60      0.75        15

    accuracy                           0.87        45
   macro avg       0.90      0.87      0.86        45
weighted avg       0.90      0.87      0.86        45

In [36]:
#sigmoid kernal
svc=SVC(kernel="sigmoid")
svc.fit(X_train_scaled,y_train)
y_pred=svc.predict(X_test_scaled)

print("accuracy : ",accuracy_score(y_test,y_pred))
print("classification report : ",classification_report(y_test,y_pred))

accuracy :  0.9111111111111111
classification report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.92      0.80      0.86        15
           2       0.82      0.93      0.88        15

    accuracy                           0.91        45
   macro avg       0.92      0.91      0.91        45
weighted avg       0.92      0.91      0.91        45